const types = require('../../client/src/constants/types');

module.exports = {
  bursaryWindowStatuses: {
    active: 'active',
    inActive: 'in-active',
  },
  bursaryApplicationStatuses: {
    request: 'request',
    preApproved: 'pre-approved',
    approved: 'approved',
    completed: 'completed',
    rejected: 'rejected',
  },
  bursaryTypes: {
    typeOfSchool: [
      'State-run or state-funded school - selective on academic, faith or other grounds',
      'State-run or state-funded school - non-selective',
      'Independent or fee-paying school - bursary',
      'Independent or fee-paying school - no bursary',
      'Attended school outside the UK',
      'Don’t know',
      "I'd prefer not to say",
      'Other (please specify)',
    ],
    highestLevelOfQualifications: [
      'At least one has a degree level qualification',
      'Qualifications below degree level',
      'No formal qualifications',
      'Don’t know',
      'Not applicable',
      "I'd prefer not to say",
      'Other (please specify)',
    ],
    describeMainIncomeEarnerMainJob: [
      'Modern professional occupations such as: teacher/lecturer, nurse, physiotherapist, social worker, welfare officer, artist, musician, police officer (sergeant or above), software designer',
      'Clerical and intermediate occupations such as: secretary, personal assistant, clerical worker, office clerk, call centre agent, nursing auxiliary, nursery nurse',
      'Senior managers and administrators usually responsible for planning, organising and co-ordinating work and for finance such as: finance manager, chief executive',
      'Technical and craft occupations such as: motor mechanic, fitter, inspector, plumber, printer, tool maker, electrician, gardener, train driver',
      'Semi-routine manual and service occupations such as: postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, receptionist, sales assistant',
      'Routine manual and service occupations such as: HGV driver, van driver, cleaner, porter, packer, sewing machinist, messenger, labourer, waiter / waitress, bar staff',
      'Middle or junior managers such as: office manager, retail manager, bank manager, restaurant manager, warehouse manager, publican',
      'Traditional professional occupations such as: accountant, solicitor, medical practitioner, scientist, civil/mechanical engineer',
      "Long term unemployed (claimed Jobseeker's Allowance or earlier unemployment benefit for more than a year)",
      'Retired',
      'Not applicable',
      'Don’t know',
      "I'd prefer not to say",
    ],
    numberOfPeopleKnowBefore16: [
      '1-3',
      '3-5',
      '5 or more',
      'Not applicable',
      "I'd prefer not to say",
    ],
    typeOfUniversity: [
      'Oxford or Cambridge',
      'Other Russell Group',
      'So-called red brick university',
      'Not applicable, I have not attended university',
      'I attended a university outside of the UK',
      'Unsure',
      "I'd prefer not to say",
    ],
    eligibleForFreeSchoolMeals: [
      'Yes',
      'No',
      'Not applicable (Finished school before 1980 or went to school overseas)',
      'Don’t know',
      "I'd prefer not to say",
    ],
    comingFromLowerSociolEconomicBackground: [
      'Yes',
      'No',
      'Don’t know',
      "I'd prefer not to say",
    ],
    householdMembersSpeakOtherLanguage: [
      'Yes - Please State',
      'No',
      "I'd prefer not to say",
    ],
    annualHouseholdIncome: [
      'Under £10k',
      '£10-25k',
      '£25-50k',
      '£50-100k',
      'Over £100k',
      "I'd prefer not to say",
    ],
    statusOfHome: [
      'Owner',
      'Renter',
      'Living with Parents',
      'Other (please specify if comfortable)',
      'Unknown',
      "I'd prefer not to say",
    ],
    anyHouseholdReceiveTheFollowing: [
      'Universal Credit',
      'Housing Benefit',
      'Council Tax Benefit',
      'Disability Allowance',
      'State Pension',
      'Other Benefit or Government assistance',
      'None of the above',
      "I'd prefer not to say",
    ],

    benefitFromNepotism: ['Yes', 'No', 'Unsure', "I'd prefer not to say"],
    peopleYouKnowSocially: [
      'Secretary, Nurse, Teacher, Cleaner',
      'University Lecturer, Artist, Electrician, Office Manager',
      'Lorry Driver, Shop Assistant, Postal Worker, Farm Worker',
      'Scientist, Chief Executive, Accountant, Software Designer',
    ],
    accentAffectsPotentialEmployers: [
      'Positive',
      'Negative',
      'Neutral',
      "I'm not aware",
      "I'd prefer not to say",
    ],
    parentsSupportiveOfCareer: ['Yes', 'No', "I'd prefer not to say"],
  },
  types,
};
