module.exports = {
  types: {
    sexualOrientation: [
      'Bisexual',
      'Gay',
      'Heterosexual',
      'Lesbian',
      'Other/not listed',
      'Queer',
      'Questioning',
      'I’d prefer not to say',
    ],
    ethnicity: [
      'White British',
      'White Gypsy/Irish Traveller',
      'White Irish',
      'White/White European',
      'Other White background (leads to text input option)',
      'Hispanic or Latinx',
      'Asian Bangladeshi',
      'Asian British',
      'Asian Chinese',
      'Asian Indian',
      'Asian Pakistani',
      'Other Asian background (leads to text input option)',
      'Black African',
      'Black British',
      'Black Caribbean',
      'African American',
      'Other Black background ((leads to text input option)',
      'Mixed/Multiple ethnic background (leads to text input option)',
      'Middle Eastern/Arab',
      'I’d prefer not to say',
    ],
    parentsWorkInPress: [
      'Mom',
      'Dad',
      'Both',
      'Neither',
      "I'd prefer not to say",
    ],
    gender: [
      'Female',
      'Intersex',
      'Male',
      'Non-binary/third gender',
      'Prefer not to self-describe',
      'Prefer not to self-identify',
      'Transgender female',
      'Transgender male',
      'Other/not listed *(this then gives them input to enter)*',
      'I’d prefer not to say',
    ],
    disability: [
      'Yes, I have (or have previously had) a visible disability',
      'Yes, I have (or have previously had) an invisible disability',
      "No, I don't have a disability",
      "I'd prefer not to say",
    ],
    disabilityYes: [
      'Hearing',
      'Learning difficulties',
      'Long term illness',
      'Manual dexterity or coordination',
      'Mental Health',
      'Mobility',
      'Reduced physical capacity',
      'Speech',
      'Visual',
      'Other (text box)',
      'I’d prefer not to say',
    ],

    interests: [
      'Broadcast',
      'Radio',
      'TV News',
      'TV Programming',
      'Documentary',
      'Print',
      'Online',
      'Social Media',
      'Publishing',
      'PR',
      'Other',
    ],
    workingArea: [
      'Broadcast',
      'Radio',
      'TV News',
      'TV Programming',
      'Documentary',
      'Print',
      'Online',
      'Social Media',
      'Publishing',
      'PR',
      'Other',
    ],
    areasOfInterest: ['Foreign Affairs'],
    accommodationChecklist: [
      'Lock on the bathroom door',
      'Lock on the bedroom door',
      'Spare key for intern',
      'I’ll be there to welcome them on their first day',
      'WiFi code made available',
      'Bed linen including towel',
      'Space provided in fridge and cupboard for intern’s food',
      'I can provide info for someone they can contact if I’m not available',
      'None of these',
    ],
    degreeLevel: [
      `None`,
      `GCSEs`,
      `A levels or equivalent (International Baccalaureate diploma, HNC, NVQ Level 4-5, HNC, HND, RSA Higher Diploma, BTEC Higher Level, non-UK qualification equivalent))`,
      `Undergraduate degree or equivalent`,
      `Professional qualification (e.g. teaching, nursing, accountancy)`,
      `Master’s degree`,
      `PhD/Doctoral degree`,
      `I’d prefer not to say`,
    ],
    parentProfession: [
      'Modern professional occupations such as (teacher, nurse, physiotherapist, social worker, musician, police officer (sergeant or above), software designer)',
      'Clerical and intermediate occupations (such as secretary, personal assistant, clerical worker, call centre agent, nursery nurse)',
      'Senior managers or administrators usually responsible for planning, organising and co-ordinator work, and for finance (such as finance manager, chief executive)',
      'Technical and craft occupations (such as motor mechanic, plumber, printer, electrician, gardener, train driver)',
      'Semi-routine manual and service occupations (such as postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, sales assistant)',
      'Routine manual and service occupations (such as lorry driver, cleaner, porter, packer, labourer, waiter/waitress, bar staff)',
      'Middle or junior managers (such as office manager, retail manager, bank manager, restaurant manager, warehouse manager)',
      'Traditional professional occupations (such as accountant, solicitor, medical practitioner, scientist, civil / mechanical engineer)',
      'Unemployed',
      "I'd prefer not to say",
    ],
    religion: [
      'Christian - Protestant',
      'Christian - Catholic',
      'Spiritual',
      'Buddhist',
      'Muslim',
      'Hindu',
      'Sikh',
      'Other',
      'No religion or belief/Atheist',
      'I’d prefer not to say',
    ],
    neurodivergent: ['Yes', 'No', 'I’d prefer not to say'],
    neurodivergentYes: [
      'ADHD',
      'On the Autism spectrum',
      `Asperger's syndrome`,
      'Dyslexia',
      'Dyscalculia',
      'Epilepsy',
      'Hyperlexia',
      'Dyspraxia',
      'Obsessive-compulsive disorder (OCD)',
      'Tourette syndrome (TS)',
      'I’d prefer not to say',
    ],
    childCare: ['Yes', 'No', 'I’d prefer not to say'],
    illCare: [
      'Yes, 50 or more hours a week',
      'Yes, 1-19 hours a week',
      'Yes, 20-49 hours a week',
      'No',
      'I’d prefer not to say',
    ],
    class: [
      'Precariat i.e. deprived',
      'Traditional Working Class',
      'Emergent Service Workers',
      'Technical Middle Class',
      'New Affluent Workers',
      'Established Middle Class',
      'Elite/Upper class',
      'I don’t consider myself as belonging to any one class',
      'I’d prefer not to say',
    ],
  },
};
