module.exports = {
  sexualOrientation: [
    'Bisexual',
    'Gay',
    'Heterosexual',
    'Lesbian',
    'Other/not listed',
    'Queer',
    'Questioning',
    'I’d prefer not to say',
  ],
  ethnicity: [
    'White British',
    'White Gypsy/Irish Traveller',
    'White Irish',
    'White/White European',
    'Other White background (leads to text input option)',
    'Hispanic or Latinx',
    'Asian Bangladeshi',
    'Asian British',
    'Asian Chinese',
    'Asian Indian',
    'Asian Pakistani',
    'Other Asian background (leads to text input option)',
    'Black African',
    'Black British',
    'Black Caribbean',
    'African American',
    'Other Black background ((leads to text input option)',
    'Mixed/Multiple ethnic background (leads to text input option)',
    'Middle Eastern/Arab',
    'I’d prefer not to say',
  ],
  parentsWorkInPress: [
    'Mom',
    'Dad',
    'Both',
    'Neither',
    "I'd prefer not to say",
  ],
  gender: [
    'Female',
    'Intersex',
    'Male',
    'Non-binary/third gender',
    'Prefer not to self-describe',
    'Prefer not to self-identify',
    'Transgender female',
    'Transgender male',
    'Other/not listed',
    'I’d prefer not to say',
  ],

  disability: [
    'Yes, I have (or have previously had) a visible disability',
    'Yes, I have (or have previously had) an invisible disability',
    "No, I don't have a disability",
    "I'd prefer not to say",
  ],
  disabilityYes: [
    'Hearing',
    'Learning difficulties',
    'Long term illness',
    'Manual dexterity or coordination',
    'Mental Health',
    'Mobility',
    'Reduced physical capacity',
    'Speech',
    'Visual',
    'Other',
    'I’d prefer not to say',
  ],
  interests: [
    'Broadcast',
    'Radio',
    'TV News',
    'TV Programming',
    'Documentary',
    'Print',
    'Online',
    'Social Media',
    'Publishing',
    'PR',
    'Multimedia',
    'Sports',
    'International',
    'Arts',
    'Breaking News',
    'Opinion writing',
    'Video',
    'Commissioning',
    'Investigative',
    'Photo-journalism',
  ],
  degreeLevel: [
    `None`,
    `GCSEs`,
    `A levels or equivalent (International Baccalaureate diploma, HNC, NVQ Level 4-5, HNC, HND, RSA Higher Diploma, BTEC Higher Level, non-UK qualification equivalent))`,
    `Undergraduate degree or equivalent`,
    `Professional qualification (e.g. teaching, nursing, accountancy)`,
    `Master’s degree`,
    `PhD/Doctoral degree`,
    `I’d prefer not to say`,
  ],
  parentProfession: [
    'Modern professional occupations such as (teacher, nurse, physiotherapist, social worker, musician, police officer (sergeant or above), software designer)',
    'Clerical and intermediate occupations (such as secretary, personal assistant, clerical worker, call centre agent, nursery nurse)',
    'Senior managers or administrators usually responsible for planning, organising and co-ordinator work, and for finance (such as finance manager, chief executive)',
    'Technical and craft occupations (such as motor mechanic, plumber, printer, electrician, gardener, train driver)',
    'Semi-routine manual and service occupations (such as postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, sales assistant)',
    'Routine manual and service occupations (such as lorry driver, cleaner, porter, packer, labourer, waiter/waitress, bar staff)',
    'Middle or junior managers (such as office manager, retail manager, bank manager, restaurant manager, warehouse manager)',
    'Traditional professional occupations (such as accountant, solicitor, medical practitioner, scientist, civil / mechanical engineer)',
    'Unemployed',
    "I'd prefer not to say",
  ],
  workingArea: [
    'Broadcast',
    'Radio',
    'TV News',
    'TV Programming',
    'Documentary',
    'Print',
    'Online',
    'Social Media',
    'Publishing',
    'PR',
    'Other',
  ],
  accommodationChecklist: [
    'Lock on the bathroom door',
    'Lock on the bedroom door',
    'Spare key for intern',
    'I’ll be there to welcome them on their first day',
    'WiFi code made available',
    'Bed linen including towel',
    'Space provided in fridge and cupboard for intern’s food',
    'I can provide info for someone they can contact if I’m not available',
    'None of these',
  ],
  religion: [
    'Christian - Protestant',
    'Christian - Catholic',
    'Spiritual',
    'Buddhist',
    'Muslim',
    'Hindu',
    'Sikh',
    'Other',
    'No religion or belief/Atheist',
    'I’d prefer not to say',
  ],
  neurodivergent: ['Yes', 'No', 'I’d prefer not to say'],
  neurodivergentYes: [
    'ADHD',
    'On the Autism spectrum',
    `Asperger's syndrome`,
    'Dyslexia',
    'Dyscalculia',
    'Epilepsy',
    'Hyperlexia',
    'Dyspraxia',
    'Obsessive-compulsive disorder (OCD)',
    'Tourette syndrome (TS)',
    'I’d prefer not to say',
  ],
  childCare: ['Yes', 'No', 'I’d prefer not to say'],
  illCare: [
    'Yes, 50 or more hours a week',
    'Yes, 1-19 hours a week',
    'Yes, 20-49 hours a week',
    'No',
    'I’d prefer not to say',
  ],
  belongToClass: [
    'Precariat i.e. deprived',
    'Traditional Working Class',
    'Emergent Service Workers',
    'Technical Middle Class',
    'New Affluent Workers',
    'Established Middle Class',
    'Elite/Upper class',
    'I don’t consider myself as belonging to any one class',
    'I’d prefer not to say',
  ],
  typeOfSchool: [
    'State-run or state-funded school - selective on academic, faith or other grounds',
    'State-run or state-funded school - non-selective',
    'Independent or fee-paying school - bursary',
    'Independent or fee-paying school - no bursary',
    'Attended school outside the UK',
    'Don’t know',
    "I'd prefer not to say",
    'Other (please specify)',
  ],
  eligibleForFreeSchoolMeals: [
    'Yes',
    'No',
    'I don’t know',
    'I’d prefer not to say',
  ],
  describeMainIncomeEarnerMainJob: [
    'Modern professional occupations such as (teacher, nurse, physiotherapist, social worker, musician, police officer (sergeant or above), software designer)',
    'Clerical and intermediate occupations (such as secretary, personal assistant, clerical worker, call centre agent, nursery nurse)',
    'Senior managers or administrators usually responsible for planning, organising and co-ordinator work, and for finance (such as finance manager, chief executive)',
    'Technical and craft occupations (such as motor mechanic, plumber, printer, electrician, gardener, train driver)',
    'Semi-routine manual and service occupations (such as postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, sales assistant)',
    'Routine manual and service occupations (such as lorry driver, cleaner, porter, packer, labourer, waiter/waitress, bar staff)',
    'Middle or junior managers (such as office manager, retail manager, bank manager, restaurant manager, warehouse manager)',
    'Traditional professional occupations (such as accountant, solicitor, medical practitioner, scientist, civil / mechanical engineer)',
    'Unemployed',
    'I’d prefer not to say',
  ],
  highestLevelOfQualifications: [
    'At least one has a degree level qualification',
    'Qualifications below degree level',
    'Don’t know',
    'Not applicable',
    'Other',
  ],
  hostWorkingArea: [
    'Broadcast',
    'Radio',
    'TV News',
    'TV Programming',
    'Documentary',
    'Print',
    'Online',
    'Social Media',
    'Magazine',
    'Publishing',
    'PR',
    'Multimedia',
    'Sports',
    'International',
    'Arts',
    'Breaking News',
    'Opinion writing',
    'Video',
    'Commissioning',
    'Investigative',
    'Photo-journalism',
    'Other',
  ],
  bursaryTypes: {
    typeOfSchool: [
      'State-run or state-funded school - selective on academic, faith or other grounds',
      'State-run or state-funded school - non-selective',
      'Independent or fee-paying school - bursary',
      'Independent or fee-paying school - no bursary',
      'Attended school outside the UK',
      'Don’t know',
      "I'd prefer not to say",
      'Other (please specify)',
    ],
    highestLevelOfQualifications: [
      'At least one has a degree level qualification',
      'Qualifications below degree level',
      'No formal qualifications',
      'Don’t know',
      'Not applicable',
      "I'd prefer not to say",
      'Other (please specify)',
    ],
    describeMainIncomeEarnerMainJob: [
      'Modern professional occupations such as: teacher/lecturer, nurse, physiotherapist, social worker, welfare officer, artist, musician, police officer (sergeant or above), software designer',
      'Clerical and intermediate occupations such as: secretary, personal assistant, clerical worker, office clerk, call centre agent, nursing auxiliary, nursery nurse',
      'Senior managers and administrators usually responsible for planning, organising and co-ordinating work and for finance such as: finance manager, chief executive',
      'Technical and craft occupations such as: motor mechanic, fitter, inspector, plumber, printer, tool maker, electrician, gardener, train driver',
      'Semi-routine manual and service occupations such as: postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, receptionist, sales assistant',
      'Routine manual and service occupations such as: HGV driver, van driver, cleaner, porter, packer, sewing machinist, messenger, labourer, waiter / waitress, bar staff',
      'Middle or junior managers such as: office manager, retail manager, bank manager, restaurant manager, warehouse manager, publican',
      'Traditional professional occupations such as: accountant, solicitor, medical practitioner, scientist, civil/mechanical engineer',
      "Long term unemployed (claimed Jobseeker's Allowance or earlier unemployment benefit for more than a year)",
      'Retired',
      'Not applicable',
      'Don’t know',
      "I'd prefer not to say",
    ],
    numberOfPeopleKnowBefore16: [
      '1-3',
      '3-5',
      '5 or more',
      'Not applicable',
      "I'd prefer not to say",
    ],
    typeOfUniversity: [
      'Oxford or Cambridge',
      'Other Russell Group',
      'So-called red brick university',
      'Not applicable, I have not attended university',
      'I attended a university outside of the UK',
      'Unsure',
      "I'd prefer not to say",
    ],
    eligibleForFreeSchoolMeals: [
      'Yes',
      'No',
      'Not applicable (Finished school before 1980 or went to school overseas)',
      'Don’t know',
      "I'd prefer not to say",
    ],
    comingFromLowerSociolEconomicBackground: [
      'Yes',
      'No',
      'Don’t know',
      "I'd prefer not to say",
    ],
    householdMembersSpeakOtherLanguage: [
      'Yes - Please State',
      'No',
      "I'd prefer not to say",
    ],
    annualHouseholdIncome: [
      'Under £10k',
      '£10-25k',
      '£25-50k',
      '£50-100k',
      'Over £100k',
      "I'd prefer not to say",
    ],
    statusOfHome: [
      'Owner',
      'Renter',
      'Living with Parents',
      'Other (please specify if comfortable)',
      'Unknown',
      "I'd prefer not to say",
    ],
    anyHouseholdReceive: [
      'Universal Credit',
      'Housing Benefit',
      'Council Tax Benefit',
      'Disability Allowance',
      'State Pension',
      'Other Benefit or Government assistance',
      'None of the above',
      "I'd prefer not to say",
    ],

    benefitFromNepotism: ['Yes', 'No', 'Unsure', "I'd prefer not to say"],
    peopleYouKnowSocially: [
      'Secretary, Nurse, Teacher, Cleaner',
      'University Lecturer, Artist, Electrician, Office Manager',
      'Lorry Driver, Shop Assistant, Postal Worker, Farm Worker',
      'Scientist, Chief Executive, Accountant, Software Designer',
    ],
    accentAffectsPotentialEmployers: [
      'Positive',
      'Negative',
      'Neutral',
      "I'm not aware",
      "I'd prefer not to say",
    ],
    parentsSupportiveOfCareer: ['Yes', 'No', "I'd prefer not to say"],
  },
};
